#!/bin/sh -e

export DESTDIR="$1"

meson \
    --prefix=/usr \
    -Dxwayland=disabled \
    -Ddefault-wallpaper=false \
    -Dzsh-completions=false \
    -Dbash-completions=false \
    -Dfish-completions=false \
    -Dtray=disabled \
    -Dswaybar=false \
    -Dswaynag=false \
    . build

ninja -C build
ninja -C build install
