#!/bin/sh -e

meson \
    --prefix=/usr \
    -Ddefault_library=both \
    -Dexamples=false \
    -Dxcb-errors=disabled \
    -Dxwayland=disabled \
    -Drenderers=gles2 \
    -Denum-backend=demi \
    . build

ninja -C build
ninja -C build install
